In [1]:
import pandas as pd
import numpy as np

In [2]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
#reshaping array into 3 rows and 5 columns

In [4]:
np.arange(0,15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
#to make a table

In [7]:
data = pd.DataFrame(np.arange(0,15).reshape(3,5),index=['R1','R2','R3'],columns=['c1','c2','c3','c4','c5'])

In [8]:
data

c1  c2  c3  c4  c5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14

In [9]:
#to convert data into excel sheet
data.to_csv('test1.csv')

In [10]:
#accessing the elements
data.loc['R2']

c1    5
c2    6
c3    7
c4    8
c5    9
Name: R2, dtype: int32

In [11]:
type(data.loc['R1'])

pandas.core.series.Series

In [12]:
#To extract whole table
data.iloc[:,:]

c1  c2  c3  c4  c5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14

In [19]:
#To remove a coloumn
data.iloc[:,2:]

c3  c4  c5
R1   2   3   4
R2   7   8   9
R3  12  13  14

In [22]:
# if you need  3 rows and 2 coloums
data.iloc[0:3,0:2]

c1  c2
R1   0   1
R2   5   6
R3  10  11

In [25]:
#convert data back into array
data1 = data.iloc[:,:].values

In [26]:
data1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
#to know the value at the position
data1[0][1]

1

In [30]:
data1[1][3]

8

In [33]:
num = len(data1)
for i in range(num):
    print([i][0])


0
1
2


In [34]:
#NEWTONS DIVIDED DIFFERENCE
import pandas as pd
def New_interpolation(x,y,xi):
    n = len(x)   # number of datapoints 
    
# initialize divided difference, f(x) values at different degrees, and error value

    fdd = [[None for x in range(n)] for x in range(n)]
    yint =[None for x in range(n)]
    err = [None for x in range(n)]
    
# Finding divided difference
    
    for i in range(n):
        fdd[i][0] = y[i]
    for j in range(1,n):
        for i in range(n-j):
            fdd[i][j] = (fdd[i+1][j-1] - fdd[i][j-1])/(x[i+j]-x[i])
# Printing fdd here

    fdd_table = pd.DataFrame(fdd)
    print(fdd_table)
    
# interpolating xi
    xterm = 1
    yint[0] = fdd[0][0]
    for order in range(1,n):
        xterm = xterm * (xi - x[order-1])
        yint2 = yint[order-1] + fdd[0][order]*xterm
        err[order-1] = yint2 - yint[order-1]
        yint[order] = yint2
        
# returning a map for pandas dataframe
    return map(lambda y,e : [y,e], yint, err)

In [35]:
x = [1, 4, 6, 5, 3, 1.5, 2.5, 3.5]
y = [0,1.3862944, 1.7917595, 1.6094379, 1.0986123, 0.4054641, 0.9162907, 1.2527630]
a = New_interpolation(x,y,2)
df = pd.DataFrame(a,columns=['f(x)','error'])

          0         1         2         3         4         5         6  \
0  0.000000  0.462098 -0.051873  0.007866 -0.001956  0.000908 -0.000301   
1  1.386294  0.202733 -0.020411  0.003953 -0.001502  0.000456 -0.000110   
2  1.791759  0.182322 -0.024364  0.007709 -0.002186  0.000511       NaN   
3  1.609438  0.255413 -0.059053  0.015361 -0.003464       NaN       NaN   
4  1.098612  0.462099 -0.097456  0.020557       NaN       NaN       NaN   
5  0.405464  0.510827 -0.087177       NaN       NaN       NaN       NaN   
6  0.916291  0.336472       NaN       NaN       NaN       NaN       NaN   
7  1.252763       NaN       NaN       NaN       NaN       NaN       NaN   

          7  
0  0.000076  
1       NaN  
2       NaN  
3       NaN  
4       NaN  
5       NaN  
6       NaN  
7       NaN  


In [36]:
df

f(x)     error
0  0.000000  0.462098
1  0.462098  0.103746
2  0.565844  0.062924
3  0.628769  0.046953
4  0.675722  0.021791
5  0.697513 -0.003616
6  0.693897 -0.000459
7  0.693438       NaN

In [39]:
x = [2,6,8,10,5]
n = len(x)
lst = []
for x in range(n):
    a = None
    lst.append(a)
    

In [40]:
lst

[None, None, None, None, None]

In [41]:
x = [1,4,6,3,6,8,9,12,13,14,13,17]
n = len(x)
[None for i in range(n)]

[None, None, None, None, None, None, None, None, None, None, None, None]